import { StyleSheet } from 'react-native';
import { Colors, Typography } from '../theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  settingsBtn: { position: "absolute", top: 35, right: 20 },
  locateBtn: { position: "absolute", top: 95, right: 20 },
  iconWrapper: {
    padding: 12,
    borderRadius: 25,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.hairline,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  inlineIcon: {
    width: 17,
    height: 17,
    resizeMode: "contain",
    marginHorizontal: 2,
    transform: [{ translateY: 3 }],
  },

  devPanel: {
    position: "absolute",
    right: 10,
    top: "50%",
    transform: [{ translateY: -100 }],
    backgroundColor: "rgba(200, 50, 50, 0.85)",
    padding: 12,
    borderRadius: 12,
    zIndex: 1000,
    elevation: 1000,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  devTitle: {
    fontFamily: Typography.heading,
    color: "#fff",
    fontSize: 10,
    marginBottom: 6,
    textAlign: "center",
    letterSpacing: 1,
  },
  devBtn: {
    backgroundColor: Colors.bgElevated,
    paddingHorizontal: 6,
    paddingVertical: 6,
    borderRadius: 8,
    marginBottom: 5,
    elevation: 2,
  },
  devBtnText: {
    fontFamily: Typography.bodyBold,
    color: "rgba(200, 50, 50, 1)",
    fontSize: 9,
    textAlign: "center",
  },

  topLeft: { position: "absolute", top: 35, left: 20 },
  balancePill: {
    overflow: "hidden",
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 1,
    borderColor: Colors.hairline,
    justifyContent: "center",
    alignItems: "center",
  },
  balanceText: {
    fontFamily: Typography.bodyBold,
    color: Colors.textPrimary,
    fontSize: 13,
    textAlign: "center",
  },

  upcomingRow: { flexDirection: "row", alignItems: "center" },
  plusBtn: {
    width: 54,
    height: 54,
    backgroundColor: Colors.glassBtnBg,
    borderRadius: 27,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.gold,
    shadowOpacity: 0.55,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  upcomingScroll: { marginLeft: 12, maxWidth: 220 },
  upcomingIcon: {
    width: 40,
    height: 40,
    backgroundColor: Colors.glassBtnBg,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    shadowColor: Colors.gold,
    shadowOpacity: 0.45,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 5,
  },
  upcomingInitial: {
    fontFamily: Typography.bodyBold,
    color: Colors.textPrimary,
    fontSize: 15,
  },

  bottomBar: {
    position: "absolute",
    bottom: 35,
    left: 20,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  dateSliderContainer: {
    flex: 1,
    marginRight: 15,
    borderRadius: 24,
    paddingVertical: 4,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.hairline,
    flexDirection: "row",
    alignItems: "center",
  },
  scrollIndicatorLeft: {
    position: "absolute",
    left: 0,
    zIndex: 10,
    padding: 8,
  },
  scrollIndicatorRight: {
    position: "absolute",
    right: 0,
    zIndex: 10,
    padding: 8,
  },
  datePill: {
    backgroundColor: "transparent",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 18,
    marginRight: 6,
  },
  datePillActive: {
    backgroundColor: Colors.gold,
  },
  datePillText: {
    fontFamily: Typography.bodySemibold,
    color: Colors.textSecondary,
    fontSize: 13,
  },
  datePillTextActive: { color: '#1A2421' },

  filterBtn: { borderRadius: 24, overflow: "hidden" },
  filterBtnWrapper: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: Colors.hairline,
  },
  filterBtnText: {
    fontFamily: Typography.bodySemibold,
    color: Colors.textSecondary,
    fontSize: 13,
  },

  wizardCat: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.hairline,
    marginRight: 8,
    backgroundColor: Colors.bgInput,
  },
  wizardCatText: {
    fontFamily: Typography.bodyBold,
    fontSize: 13,
    color: Colors.textPrimary,
    marginLeft: 6,
  },
  wizardSubCat: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: Colors.bgInput,
    borderWidth: 1,
    borderColor: Colors.hairline,
    marginRight: 8,
  },
  wizardSubCatActive: {
    backgroundColor: Colors.goldDim,
    borderColor: Colors.goldBorder,
  },
  wizardSubCatText: {
    fontFamily: Typography.bodySemibold,
    fontSize: 13,
    color: Colors.textSecondary,
  },

  filterGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 15,
  },
  filterCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.hairline,
    backgroundColor: Colors.bgInput,
    width: "48%",
  },
  filterCardActive: {
    borderColor: Colors.goldBorder,
    backgroundColor: Colors.goldDim,
  },
  filterCardText: {
    fontFamily: Typography.bodyBold,
    fontSize: 14,
    marginLeft: 8,
    color: Colors.textPrimary,
  },

  glassWrapperBottom: {
    position: "absolute",
    bottom: 35,
    left: 20,
    right: 20,
    borderRadius: 24,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 25,
  },
  glassWrapperBottomFull: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "60%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 30,
    zIndex: 100,
    elevation: 100,
  },
  glassWrapperTop: {
    position: "absolute",
    top: 40,
    left: 20,
    right: 20,
    borderRadius: 24,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 20,
    zIndex: 100,
    elevation: 100,
  },

  glassPanelBottom: {
    padding: 25,
    backgroundColor: Colors.bg,
    borderWidth: 1,
    borderColor: Colors.hairline,
  },
  glassPanelBottomFull: {
    padding: 30,
    backgroundColor: Colors.bg,
    borderWidth: 1,
    borderColor: Colors.hairline,
    flex: 1,
  },
  glassPanelTop: { padding: 25, backgroundColor: Colors.bg },

  panelTitle: {
    fontFamily: Typography.headline,
    fontSize: 24,
    color: Colors.textPrimary,
    marginBottom: 20,
  },
  panelTitleDark: {
    fontFamily: Typography.headline,
    fontSize: 22,
    color: Colors.textPrimary,
    marginBottom: 5,
  },
  panelSubDark: {
    fontFamily: Typography.body,
    fontSize: 14,
    color: Colors.textSecondary,
    marginBottom: 20,
  },
  input: {
    fontFamily: Typography.body,
    borderWidth: 1,
    borderColor: Colors.borderInput,
    backgroundColor: Colors.bgInput,
    borderRadius: 16,
    padding: 16,
    marginBottom: 15,
    fontSize: 15,
    color: Colors.textPrimary,
  },
  suggestionsContainer: {
    backgroundColor: Colors.bgElevated,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.hairline,
    maxHeight: 120,
    overflow: "hidden",
    marginTop: -5,
    marginBottom: 15,
  },
  suggestionItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.hairline,
  },
  suggestionText: {
    fontFamily: Typography.body,
    fontSize: 13,
    color: Colors.textPrimary,
  },

  row: { flexDirection: "row", gap: 10, justifyContent: "flex-end" },
  btnPrimary: {
    backgroundColor: Colors.glassBtnBg,
    paddingHorizontal: 24,
    height: 56,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: Colors.gold,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  btnPrimaryFull: {
    backgroundColor: Colors.glassBtnBg,
    height: 56,
    borderRadius: 9999,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    width: "100%",
    marginTop: 20,
    borderWidth: 1,
    borderColor: Colors.gold,
  },
  btnPrimaryText: {
    fontFamily: Typography.bodyBold,
    color: Colors.textPrimary,
    fontSize: 15,
    letterSpacing: 0.2,
  },
  btnSecondary: {
    backgroundColor: "transparent",
    paddingHorizontal: 15,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
  },
  btnSecondaryText: {
    fontFamily: Typography.bodyBold,
    color: Colors.textSecondary,
    fontSize: 15,
  },
  btnSecondaryTextDark: {
    fontFamily: Typography.bodyBold,
    color: Colors.textSecondary,
    fontSize: 15,
  },

  chatHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  chatTitle: {
    fontFamily: Typography.headline,
    fontSize: 22,
    color: Colors.textPrimary,
  },
  chatSub: {
    fontFamily: Typography.body,
    fontSize: 12,
    color: Colors.gold,
    marginTop: 4,
  },
  closeIcon: { fontSize: 20, color: Colors.textSecondary, paddingHorizontal: 5 },
  chatLoc: {
    fontFamily: Typography.body,
    fontSize: 13,
    color: Colors.textLight,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: Colors.hairline,
    marginBottom: 15,
  },

  chatLocked: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 30,
  },
  chatLockedIco: { fontSize: 45, marginBottom: 15 },
  chatLockedTitle: {
    fontFamily: Typography.headline,
    fontSize: 24,
    color: Colors.textPrimary,
    marginBottom: 10,
    textAlign: "center",
  },
  chatLockedSub: {
    fontFamily: Typography.body,
    fontSize: 15,
    color: Colors.textSecondary,
    textAlign: "center",
    lineHeight: 22,
  },

  chatOpen: { flex: 1 },
  chatScroll: { flex: 1 },
  chatBubble: {
    backgroundColor: "rgba(255,255,255,0.06)",
    padding: 18,
    borderRadius: 20,
    alignSelf: "flex-start",
    borderBottomLeftRadius: 5,
    borderWidth: 1,
    borderColor: Colors.hairline,
  },
  chatText: { fontFamily: Typography.body, color: Colors.textPrimary, fontSize: 14 },
  chatInputRow: {
    flexDirection: "row",
    gap: 10,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: Colors.hairline,
  },
  chatInput: {
    flex: 1,
    fontFamily: Typography.body,
    backgroundColor: Colors.bgInput,
    borderRadius: 20,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: Colors.borderInput,
    color: Colors.textPrimary,
  },

  pinBase: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Colors.sage,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.6)',
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 5,
  },
  pinPublic: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.gold,
  },
  pinPrivate: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "rgba(107, 142, 107, 0.2)",
    borderWidth: 1,
    borderColor: Colors.sage,
  },
  pinDraft: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.gold,
    elevation: 10,
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  pinExternal: { backgroundColor: Colors.sage },
});

